### ISSUE TITLE
Can you update the gradle version?

### ISSUE THREAD

**Issue by crucifyer** [jiusanzhou/flutter_notification_listener#26]
I newly installed android studio flutter, but I get a version error.

```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_notification_listener' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

Thanks for making a great plugin.

**Comment by crucifyer** [comment]
I modified the version number in the build.gradle file and tested it.
AndroidManifest.xml
The android:exported="true" attribute is now required in the service tag.
I haven't made an app yet, so I haven't checked whether it's possible to set it to false.

**Comment by jiusanzhou** [comment]
@crucifyer Hi, I will check it in few days, you can clone this repo to your local directory and change it by your self.

```yaml
dependencies:
   flutter:
     sdk: flutter
   flutter_notification_listener:
     path: YOUR_LOCAL_PATH
```
